apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-zxwq
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0034-tenant/tkrw-pr712-0075-0034-app/devfile-sample-zxwq@sha256:30bde195c09e2ac87af79f357e40f011cfba5e05fda1d42a8b6ca0126e0a1120
        name: my-nodejs
        resources: {}
status: {}
